### ISSUE TITLE
getCountyOptions is not defined

### ISSUE THREAD

**Issue by ethancfchen** [dennykuo/tw-city-selector#10]
`src/tw-city-selector` line `#157` `#203` 有使用 `getCountyOptions` 但沒有定義。
應是 line `#208` `function getCountryOptions`，應改正為 `getCountyOptions`

**Comment by dennykuo** [comment]
已在修正錯別字的版 v.1.0.9 中修正 : )

[src/tw-city-selector.js #208](https://github.com/dennykuo/tw-city-selector/blob/cc263c865781ad8f033d9fe94563e3090c1e1f82/src/tw-city-selector.js#L208)
