### ISSUE TITLE
請問有限制地區的功能嗎?

### ISSUE THREAD

**Issue by HaooChang** [dennykuo/tw-city-selector#11]
像城市有onlyCity，是否有限制地區的功能呢?

**Comment by dennykuo** [comment]
謝謝您的建議，已在 v1.0.10 增加此功能

### 使用方式

#### role-attribute 方式 (已補充文件中)
臺北市(大同區、萬華區)、臺中市(西區)、高雄市(不設限)

```
<div role="tw-city-selector"
     data-only="臺北市@大同區|萬華區,臺中市@西區,高雄市">
</div>
```

#### 實例方式 (尚未補充文件)

```
new TwCitySelector({
  el: '.foo',
  only: ['臺北市@大同區|萬華區', '臺中市@西區', '高雄市']
});
```

**Comment by HaooChang** [comment]
謝謝 Denny大，已經下載最新版本了，使用上很方便 👍

**Comment by dennykuo** [comment]
有時間我會再補上「除外」的縣市區域 feature

不過不敢稱為大啦 
repo 有不成熟的地方還請多給予指教~
