### ISSUE TITLE
tw-city-selector.js:281 Uncaught TypeError: Cannot read property 'dataset' of null

### ISSUE THREAD

**Issue by darklucifar** [dennykuo/tw-city-selector#13]
this.elCounty.querySelector('option:checked').dataset.index;  >>Line:281

**Comment by louiswang99** [comment]
在設定預設選擇縣市時遇到同樣的問題
但後來發現是因為傳的值是"台"而不是"臺"
或許原PO遇到的原因是這個？

**Comment by dennykuo** [comment]
@darklucifar, @louiswang99 

謝謝您們的回饋，但我試不出問題狀態，
更版到目前最新的 v1.0.12 ，或許能改善

**Comment by louiswang99** [comment]
我遇到的狀況並不是套件的問題
是因為套件裡的縣市名稱存的是"臺"不是"台"
如果預設選擇縣市(selectedCounty)給他"台北市"就會出現這個錯誤訊息

**Comment by dennykuo** [comment]
喔喔~ 我了解了
我會再抽空加上參數，可設資料源要為「台」或是「臺」
如台北、台中，抑或是臺北、臺中..等

似乎用台字比較通用，不知各位有什麼建議
