### ISSUE TITLE
是否能夠自行指定 name 的屬性值呢？

### ISSUE THREAD

**Issue by no249a002** [dennykuo/tw-city-selector#15]
在使用的時候使用 js 實例的作法，
但是因為想要把資料傳到 Google 表單裡，
因此 name 的屬性值必須使用跟 Google 表單相同的值，
不知道是否有方法可以插入希望使用的 name 值呢？

`<div class="form-item">`
`<label for="city">城市</label>`
						`<div id="city">`
							`<select name="entry.14110xxxxx" id="county"></select>`
							`<select name="entry.17531xxxxx" id="district"></select>`
							`<input type="text" name="entry.13580xxxxx" id="zip">`
						`</div>`
					`</div>`
	`<script>new TwCitySelector(`
		`{`
			`el: "#city",`
			`elCounty: "#county",`
			`elDistrict: "#district",`
			`elZipcode: "#zip"`
		`});</script>`

**Comment by dennykuo** [comment]
可以的，增加下列參數設定

```
countyFiledName: 'county', // 縣市欄位 name
districtFieldName: 'district', // 區域欄位 name
zipcodeFieldName: 'zipcode' // 郵遞區號欄位 name
```
