### ISSUE TITLE
新竹縣市應拆氛為新竹市、新竹縣

### ISSUE THREAD

**Issue by ethancfchen** [dennykuo/tw-city-selector#2]
請參考
http://c2e.ezbox.idv.tw/zipcode.php

**Comment by lackneets** [comment]
看起來沒在維護了

**Comment by dennykuo** [comment]
新竹市、新竹縣、嘉義市及嘉義縣，均修正了
感謝提供資訊！

**Comment by ethancfchen** [comment]
Welcome back~
先前還打算 fork 出去自己維護一份，看來沒這個必要了~
若有閒暇之餘我也會多多貢獻

**Comment by lackneets** [comment]
淡水鎮也請改為淡水區

**Comment by dennykuo** [comment]
已修正，謝謝提供資訊

**Comment by lackneets** [comment]
還有一個彰化縣員林鎮 → 市

**Comment by ethancfchen** [comment]
@lackneets 建議不同的問題應個別開 issues

**Comment by lackneets** [comment]
只是沒更新資料，一次修到好不就好了

**Comment by ethancfchen** [comment]
@lackneets 的確是這樣，我的建議只是在 open source 的精神下，請原作者修正問題應該清楚分明的表達。如果對於原作者的內容不甚滿意可以自行 fork 修正。

**Comment by dennykuo** [comment]
抱歉，我應更加審慎檢查資料正確性
會再將所有縣市資料檢查過 (怎麼變化這麼大...)

若造成使用上的困擾，還請多包涵，給予指教~

**Comment by ethancfchen** [comment]
@dennykuo 
沒關係，能夠分享自己的作品已經很不容易了，況且事隔已久，資料的更新本來就需要花時間維護。
open source 本來就是大家互相幫忙、互相鼓勵。
