### ISSUE TITLE
使用指定選單ele寫法時，zipcode不會被trigger

### ISSUE THREAD

**Issue by moojing** [dennykuo/tw-city-selector#23]
大大你好：
我在使用時發現，一定要將hasZipCode設定為true才能讓zipcode被觸發產生，
好像有看到一段source code是el 跟hasZipCode 擇一都可以，但後來就找不到了，
不過範例裡面是沒有設定hasZipCod的 ， 卻是不能work，能否再麻煩大大看看？
感謝！
 
```
    new TwCitySelector({
            el: '.city-selector-set',
            elCounty: '.county',
            elDistrict: '.district', 
            elZipcode: '.zipcode', 
            hasZipcode: true // Must Have
        });
```

**Comment by dennykuo** [comment]
- hasZipcode 用來設定是否要啟用「郵遞區號」欄位
- elZipcode 用來指定作用 element

hasZipcode 為 true，但沒有設置 elZipcode 時，會自動產生一個欄位 dom
但只設定 elZipcode 是不能觸發 hasZipcode 為 true 的設定

這是目前的程式設置，還請見諒~
