### ISSUE TITLE
排除特定縣市

### ISSUE THREAD

**Issue by jimmy8646** [dennykuo/tw-city-selector#24]
非常感謝這個專案，請問是否有排除特定縣市與鄉鎮的方式呢？

有看到 #11 相關的討論，不知道這個功能是否已經實現了呢？

**Comment by dennykuo** [comment]
已新增此功能，並發於發布 v2.1.0

文件說明：
https://dennykuo.github.io/tw-city-selector/#/basic?id=%E6%8E%92%E9%99%A4%E9%83%A8%E5%88%86%E7%B8%A3%E5%B8%82

https://dennykuo.github.io/tw-city-selector/#/advanced?id=except
