### ISSUE TITLE
請問如何帶值進去？

### ISSUE THREAD

**Issue by mypetertw** [dennykuo/tw-city-selector#25]
假設原本有值（編輯個人資料）
我要讓他預設「selected」好讓我提交可以帶他的值進去

**Comment by dennykuo** [comment]
如果是使用 dom 方式引用，請參考這邊：
https://dennykuo.github.io/tw-city-selector/#/basic?id=%e9%a0%90%e8%a8%ad%e9%81%b8%e5%96%ae%e5%80%bc

如果是用 new TwCitySelector() 方式的話，請參考這邊：
https://dennykuo.github.io/tw-city-selector/#/advanced?id=countyvalue
https://dennykuo.github.io/tw-city-selector/#/advanced?id=districtvalue
