### ISSUE TITLE
無法正確帶入預設值

### ISSUE THREAD

**Issue by CKCT** [dennykuo/tw-city-selector#29]
預設值若使用 台北市，但 standardWords 為 true 時

**Comment by dennykuo** [comment]
設置 standardWords 為 true  時，選單內容會使用正體字的「臺」，
因此在預設欄位值時，也需要使用正體字的「臺」來帶入，如下：

```<div role="tw-city-selector" data-standard-words data-county-value="臺北市"></div>```

或是

```
new TwCitySelector({
  el: '.city-selector',
  standardWords: true,
  countyValue: '臺北市'
});
```

請再試試，謝謝回饋！
