### ISSUE TITLE
新北市 '鎮' 應改為 '區'

### ISSUE THREAD

**Issue by ethancfchen** [dennykuo/tw-city-selector#3]
依照政府官方資訊 (https://c2e.ezbox.idv.tw/zipcode.php)
以下內容需修正：
- 三峽鎮 => 三峽區 
- 鶯歌鎮 => 鶯歌區
- 淡水鎮 => 淡水區

**Comment by dennykuo** [comment]
新北市資料修正了，謝謝您的資訊！
