### ISSUE TITLE
用ie開啟網頁時會有錯誤

### ISSUE THREAD

**Issue by williamchung0124** [dennykuo/tw-city-selector#33]
您好，感謝您的程式
一直以來都用chrome作主要的瀏覽器
現在系統在作上線的的測試
發現用IE(11)開啟時會出錯誤
同樣的問題亦出現在github的說明頁裡
https://dennykuo.github.io/tw-city-selector/#/

顯示 物件沒有支援這個屬性或方法 'includes'
大概位在：
function setStandardWords
裡的
if (county.includes(str))
            return county.replace(str, newStr);
return county;

不知是否可抽空修正或是提供修正方式？
感謝您

William

**Comment by dennykuo** [comment]
謝謝您的回饋。

推測應該是 ie11 無法支援字串的 includes 方法，資訊如下：
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes

怕您急需修正使用，可否先幫我試試在引用套件之前，添加下列的 polyfill

if (! String.prototype.includes) {
  String.prototype.includes = function(search, start) {
    'use strict';

    if (search instanceof RegExp) {
      throw TypeError('first argument must not be a RegExp');
    } 
    if (start === undefined) { start = 0; }
    return this.indexOf(search, start) !== -1;
  };
}

抱歉因工作關係，需再抽空儘速處理，若方法奏效，還勞您通知一下。
當初的確是沒有考慮到 ie11 的支援，但推測應該只有要在使用正體字「臺」這個功能下會有問題。

抱歉造成您的困擾...

**Comment by dennykuo** [comment]
Hi，發現除了上述問題，還有另一個 ie11 上 createEvent 的支援問題，
一併修正了，請安裝最新版本 v2.1.1

使用上若還有任何問題，還煩您告知。

**Comment by williamchung0124** [comment]
@dennykuo 
十分感謝，這麼快的就回應並提出解決方案
我加上您提供的PolyFill後，並改成引入2.1.1版
已可正確在IE11上執行了，十分感謝
ps：我決定要效法您的精神，之後若有一些好用的元件也放在github讓大家使用

Thank you !!!

**Comment by williamchung0124** [comment]
Dear denny
我發現IE 10在 第284行亦出現問題
(無法設定未定義或 Null 參考的屬性 'index')
_option.dataset.index = i;
如果有空的話再麻煩看看，謝謝您
萬惡的IE >< (更舊版本我直接放棄不支援了)

Best Regards,
William

**Comment by dennykuo** [comment]
Hi，抱歉忘了說明，最新版因包含 polyfill 了，不需再加上上述的 polyfill，可移除掉。

另 ie10的問題，應是不支援 dataset 方法，您可先試試找一下 ie10 dataset polyfill，我可能不會處理這個問題，但之後會在文件上特別說明。

謝謝您的協助，讓套件更完備。

**Comment by dennykuo** [comment]
針對舊版 ie 瀏覽器，我會考慮支援到 ie11，但若更早版本有問題，歡迎提出，我想找出方法，在文件中敘述。

**Comment by williamchung0124** [comment]
Dear @dennykuo 
感謝提供方向
我在這個網頁中找到答案，並測試可在ie10內正常運作
https://juejin.im/post/5d286b1d6fb9a07edd2a3fd9
(方法二)
亦感謝此文作者 silianpan
再次謝謝您提供這好用的元件及方向

**Comment by williamchung0124** [comment]
Dear @dennykuo 
我自己嘗試了一下，但只是不會出現錯誤
但無法出現鄉鎮
目前先決定暫緩，以IE11為基礎
舊版本瀏覽器則跳出警語，有機會再來研究嚕
感謝您
