### ISSUE TITLE
[建議] 依據中華郵政資料全面更新

### ISSUE THREAD

**Issue by ethancfchen** [dennykuo/tw-city-selector#4]
建議依據[中華郵政官方資料](http://www.post.gov.tw/post/internet/SearchZone/index.jsp?ID=130107)更新，細項如下：
- 彰化縣 '員林鎮' 應修正為 '員林市'
- 移除 '南海諸島', '釣魚台列嶼'，已不符合使用現況
- '釣魚臺' 依照中華郵政資料應歸屬於為 '宜蘭縣'
- '東沙群島' 及 '南沙群島' 應歸屬於 '高雄市'
- '屏東縣' '三地門' 應修正為 '三地門鄉'

**Comment by dennykuo** [comment]
已依照中華郵政資料，進行相關更新
