### ISSUE TITLE
請教下 tw-city-selector 

### ISSUE THREAD

**Issue by wangszuhung** [dennykuo/tw-city-selector#6]
想請教下 
關於您所製作的tw-city-selector
全部都透過 div包住了
那要取得使用者點選完的select 的數值要如何取得呢？
感謝您

**Comment by dennykuo** [comment]
一般預設情況下

程式產出的「縣市 select」elemet
```<select class="country" name="country">...</select>```
「區域」element
```<select class="district" name="district">...</select>```
「郵遞區號」element
```<input class="zipcode" name="zipcode" type="text" readonly="" autocomplete="off">```

可使用下列任一方式取得值
```
document.querySelector('input[name=country]').value;
document.querySelector('.country').value;

// 若使用 jQuery
$('input[name=country]').val();
$('.country').val();
```
