### ISSUE TITLE
vue3 沒辦法即時響應值

### ISSUE THREAD

**Issue by chunyenlee1996** [dennykuo/tw-city-selector#74]
我在使用變數綁定data-value時，用api的回傳把值替換掉，畫面不會跟著響應data-value改變後的值，我嘗試將值帶入select綁定的v-model，區域不會顯示帶入的值

**Comment by dennykuo** [comment]
謝謝您的回饋，請教方便貼上您簡短的使用情境程式讓我參考嗎
或是創建一個比如 codepen 的線上環境
如此我比較知道您使用上遇到的問題

我初步推測您是用 setValue(county, [district]) 這樣的方式替換值，如果是的話，我大概知道您遇到的問題

**Comment by chunyenlee1996** [comment]
好的
謝謝你
抱歉我現在才能回復
我假日電腦不在身邊
我使用的環境是vue3框架setup寫法
在template 裡面
<div class="col-2 ps-2">

<select class="county form-control form-select " v-model="cityVal"></select>
</div>
<div class="col-2 ps-2">

<select class="district form-control form-select" v-model="areaVal"></select
>
</div>
我用v-model綁定值
在 script setup 中
我使用ref 綁定值
let cityVal = ref('')
let areaVal = ref('')
在進網頁時我get api 傳來的值
在把它放進上方這兩個變數中
const { data } = await api.post('/suppliers/get-supplier', {
suppliers_uid: storeUID
})
cityVal.value = data.data.county
areaVal.value = data.data.city
可是他只有county 會顯示
我後來有在看資料寫說可以寫在data-val的attr中在getApi後將他的值替換掉，不過他沒辦法顯示，除非我一開始在創建變數時就將值放在其中
像是：
let dataVal_city = ref('台北市')
我不知道要如何將取得的api值放入預設中，不知道是不是我哪邊沒注意到，再麻煩您了，感謝！！


Denny ***@***.***> 於 2024年4月20日 週六 上午1:31寫道：

**Comment by dennykuo** [comment]
抱歉久等了

我 Vue 習慣使用「選項式」風格，這次第一次嘗試「組合式」風格，發現這種寫法有他的優點，蠻有趣的！

另在開發此套件時，並未想到在主流 framework 上的對應，所以下面的解決方案並不太優雅，
我會考慮是否另外開發對應部分主流 framework 的版本，或是增加 api 來適應。

如果您有 vue 上的使用建議，也歡迎提出！

---

您可以先試試下面的 html 及 js 看看解決方式是否符合您的需求

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>Vue test</title>
  <script src="https://cdn.jsdelivr.net/npm/tw-city-selector@2.1.1/dist/tw-city-selector.min.js"></script>
  <script type="importmap">
    {
      "imports": {
        "vue": "https://unpkg.com/vue@3/dist/vue.esm-browser.js"
      }
    }
  </script>
</head>
<body>
  <section id="app">
    <div class="city-selector-set">
      <select v-model="city" class="county"></select>
      <br>
      <select v-model="area" class="district"></select>
      <br><br>
      <button @click="setData">帶入選單值</button>
    </div>
  </section>
  
  <script type="module">
    import { createApp, ref, onMounted } from 'vue';

    const App = {
      setup() {
        let tcs = ref(null); // // 帶入 null，後續帶入套件實例
        let city = ref(''); // 帶入空字串
        let area = ref(''); // 帶入空字串
        
        onMounted(() => {
          tcs.value = new TwCitySelector({
            el: '.city-selector-set',
            elCounty: '.county',
            elDistrict: '.district'
          });
        });
        
        const setData = () => {
          tcs.value.setValue('台北市', '中正區');
        };
        
        return {
          tcs,
          city,
          area,
          setData
        };
      }
    };

    const vueVm = createApp(App).mount('#app');
    
    // ----------
    // 外部動態帶入值
    // ----------
    // setTimeout(() => {
    //  vueVm.tcs.setValue('台北市', '中正區');
    // }, 500)
  </script>
</body>
</html>
```

**Comment by chunyenlee1996** [comment]
抱歉抱歉，後續有解決好這個問題了
忘記跟你說這件事情
我這邊提供給你後來的解決方式
其實也沒有處理掉響應式的問題，不過想說他原本就是預設值，不太需要響應性，後來就有了下方的解決方式

因為測試後發現帶靜態的值是可以取得預設資料的，所以在想會不會是因為程式快慢導致，他的值還在創立變數時所帶的預設空值
所以後來將 class 的建立放在 data await 的後面，先等他取完值在做後續的動作就可以成功得到預設值了
非常感謝你的回應ＸＤ，我感到非常抱歉
// get
const getData = async () => {
try {
const { data } = await api.post('/suppliers/get-supplier', {
suppliers_uid: storeUID
})

new TwCitySelector({
el: '.city-selector-set',
elCounty: '.county', // 在 el 裡查找 element
elDistrict: '.district', // 在 el 裡查找 element
});
city_default.value = data.data.county
area_default.value = data.data.city

Denny ***@***.***> 於 2024年4月30日 週二 上午11:49寫道：
