### ISSUE TITLE
無法取得district的值

### ISSUE THREAD

**Issue by whowalkingupme** [dennykuo/tw-city-selector#84]
`var districtSelect = document.getElementById("district");
        districtSelect.addEventListener("change", function () {
            let selectedDistrictIndex = districtSelect.selectedIndex;
            console.log(selectedDistrictIndex);
            console.log(document.getElementsByTagName("option")[selectedDistrictIndex].text);
        }, false);`
他會取到county的值

**Comment by dennykuo** [comment]
抱歉晚回覆了~

我試了一下，應不是套件問題

您試試看修改其中這行
console.log(document.getElementsByTagName("option")[selectedDistrictIndex].text);
更新為
console.log(**districtSelect**.getElementsByTagName("option")[selectedDistrictIndex].text);

原來的寫法確實是直接指向到「縣市」select 沒錯，所以改用變數 districtSelect 去查找 dom 比較適當

完整如下
```
var districtSelect = document.getElementById("district");

districtSelect.addEventListener("change", function () {
    let selectedDistrictIndex = districtSelect.selectedIndex;
    console.log(selectedDistrictIndex);
    console.log(districtSelect.getElementsByTagName("option")[selectedDistrictIndex].text);
}, false);
```
